# Site settings
title: Kubernetes musings by chrislovecnm
description: "Kubernetes musings by Chris Love - aka chrislovecnm"
url: "https://chrislovecnm.com"
author:
  name: "Chris Love - chrislovecnm"
  email: "blog@cnmconsulting.net"
  url: "https://chrislovecnm.com"
  twitter: chrislovecnm
  picture: /img/chrislove-headshot-small.jpg

# Build settings
# baseurl: /
markdown: kramdown
source: .
destination: ./_site
plugins_dir: ./_plugins
permalink: /:categories/:title/
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed


# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'vendor', 'Rakefile']

twitter_username:     chrislovecnm
github_username:      chrislovecnm
twitter:
  username: chrislovecnm

social:
  name: Chris Love
  links:
    - https://twitter.com/chrislovecnm
    - https://github.com/chrislovecnm
    - https://www.linkedin.com/in/chrislovecnm


webmaster_verifications:
  bing: 9258515978EDC87C326D261B85A63F07
